services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.8
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.8
    ports:
      - "9092:9092"
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9092,OUTSIDE://127.0.0.1:9094
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE

  flume:
    build:
      context: ./flume
    volumes:
      - ./flume/flume.conf:/opt/flume/conf/flume.conf
      - ./flume/taildir_position.json:/opt/flume/taildir_position.json
      - ../logs:/opt/flume/logs
    depends_on:
      - kafka
    command: >
      sh -c "bin/flume-ng agent --conf conf --conf-file conf/flume.conf --name agent -Dflume.root.logger=DEBUG,console -Dorg.apache.flume.sink.kafka.KafkaSink.level=DEBUG"

  pgvector-db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hajimi
      POSTGRES_PASSWORD: hajimi
      POSTGRES_DB: news
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  pgdata: