services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.8
    environment:
      - TZ=Asia/Shanghai
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper/data:/var/lib/zookeeper/data
      - ./zookeeper/log:/var/lib/zookeeper/log
    privileged: true

  kafka:
    image: confluentinc/cp-kafka:7.5.8
    ports:
      - "9092:9092"
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9092,OUTSIDE://127.0.0.1:9094
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_AUTO_LEADER_REBALANCE_ENABLE=true
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=true
      - KAFKA_BROKER_ID=1
      - TZ=Asia/Shanghai
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0

  flume:
    build:
      context: ./flume
    volumes:
      - ./flume/flume.conf:/opt/flume/conf/flume.conf
      - ./flume/taildir_position.json:/opt/flume/taildir_position.json
      - ../logs:/opt/flume/logs
      - ./flume/log4j2.xml:/opt/flume/conf/log4j2.xml
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - kafka
    command: >
      sh -c "bin/flume-ng agent --conf conf --conf-file conf/flume.conf --name agent"

  pgvector-db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hajimi
      POSTGRES_PASSWORD: hajimi
      POSTGRES_DB: news
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: 'this_IS_a_SECRET_key'
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      ADMIN_FIRST_NAME: Superset
      ADMIN_LAST_NAME: Admin
      ADMIN_EMAIL: admin@example.com
    volumes:
      - ./superset:/app/superset_home
    depends_on:
      - pgvector-db
    command: >
      sh -c "pip install psycopg2-binary &&
             superset db upgrade &&
             superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@example.com --password admin &&
             superset init &&
             superset run -h 0.0.0.0 -p 8088"


volumes:
  pgdata:
